# Generated by Django 4.2.1 on 2023-06-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_status', models.CharField(choices=[('AC', 'Active'), ('FI', 'Finished'), ('CR', 'Created')], default='FI', max_length=2, verbose_name='статус рассылки')),
                ('mailing_time', models.TimeField(verbose_name='время рассылки')),
                ('mailing_periods', models.CharField(choices=[('DL', 'Daily'), ('WL', 'Weekly'), ('ML', 'Monthly')], max_length=2, verbose_name='периодичность')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_try', models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')),
                ('mailing_response', models.CharField(blank=True, max_length=255, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.mailingsettings')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_subject', models.CharField(max_length=255, verbose_name='тема письма')),
                ('mailing_body', models.CharField(max_length=500, verbose_name='тело письма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
