# Generated by Django 4.2.1 on 2023-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='mailing_time',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing_time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время конца рассылки'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing_time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время начала рассылки'),
        ),
    ]
