# Generated by Django 4.2.1 on 2023-06-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('mailing', '0002_remove_mailingsettings_mailing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client', verbose_name='клиент'),
        ),
    ]
