# Generated by Django 4.2.1 on 2023-06-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mail_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='mail_s',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.mail'),
        ),
    ]
