# Generated by Django 4.2.1 on 2023-06-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailingsettings_mail_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='mail_s',
        ),
    ]
