# Generated by Django 4.2.1 on 2023-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_mailingsettings_mail_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_setting',
            field=models.ManyToManyField(related_name='mailsset', to='mailing.mailingsettings'),
        ),
    ]
