# Generated by Django 4.2.1 on 2023-06-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_contact_email'),
        ('mailing', '0006_mail_mail_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mail_setting',
        ),
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='клиент'),
        ),
    ]
