# Generated by Django 4.2.1 on 2023-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_mail_mail_setting_alter_mail_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingtry',
            name='mailing_try_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='статус рассылки'),
        ),
    ]
