# Generated by Django 4.2.1 on 2023-07-03 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0009_alter_mailingsettings_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='all_clients',
            field=models.BooleanField(blank=True, null=True, verbose_name='все клиенты'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
    ]
