# Generated by Django 4.2.1 on 2023-07-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_mail_all_clients_alter_mail_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ('-settings',), 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
    ]
