# Generated by Django 4.2.1 on 2023-07-04 08:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0012_alter_mail_options_alter_mailingsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_cli',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mail',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_mailing', to=settings.AUTH_USER_MODEL, verbose_name='владелец рассылки'),
        ),
    ]
