# Generated by Django 4.2.1 on 2023-07-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_usertoemail'),
        ('mailing', '0014_remove_mail_mail_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.usertoemail', verbose_name='получатель рассылки'),
        ),
    ]
