# Generated by Django 4.2.1 on 2023-07-04 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0015_alter_mail_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='получатель рассылки'),
        ),
    ]
