# Generated by Django 4.2.1 on 2023-07-04 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_user_delete_usertoemail_alter_client_options_and_more'),
        ('mailing', '0016_alter_mail_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='получатель рассылки'),
        ),
    ]
