# Generated by Django 4.2.1 on 2023-07-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_alter_mail_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='owner',
        ),
    ]
