# Generated by Django 4.2.1 on 2023-07-04 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0018_remove_mail_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_mailing', to=settings.AUTH_USER_MODEL, verbose_name='владелец рассылки'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Клиенты'),
        ),
    ]
