# Generated by Django 4.2.1 on 2023-07-04 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0024_remove_mail_client_to_message_mail_client_to_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='owner',
        ),
        migrations.AddField(
            model_name='mail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
