# Generated by Django 4.2.1 on 2023-07-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0025_remove_mail_owner_mail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='user',
            new_name='author',
        ),
    ]
