# Generated by Django 4.2.1 on 2023-06-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.CharField(max_length=254, unique=True, verbose_name='контактный email'),
        ),
    ]
