# Generated by Django 4.2.1 on 2023-06-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='контактный email'),
        ),
    ]
