# Generated by Django 4.2.1 on 2023-06-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_statustype_alter_client_managers_client_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='black_list',
            field=models.BooleanField(default=False, verbose_name='черный список'),
        ),
    ]
