# Generated by Django 4.2.1 on 2023-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_mailingclient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status_type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('BASE_USER', 'Base_user'), ('CONTENT_MANAGER', 'Content_manager')], default='BASE_USER', max_length=50, verbose_name='роль'),
        ),
    ]
