# Generated by Django 4.2.1 on 2023-07-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('mailing', '0023_alter_mailingtry_mailing'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0014_alter_client_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='User',
        ),
    ]
