# Generated by Django 4.2.1 on 2023-07-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_rename_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='black_list',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активный'),
        ),
    ]
